name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: bimohxh/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: CDTRSFE/cdtrsfe.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run build && mkdir posts/.vuepress/dist/.github && mkdir posts/.vuepress/dist/.github/workflows && cp .github/gitee/mirror.yml  posts/.vuepress/dist/.github/workflows/
        BUILD_DIR: posts/.vuepress/dist/
